app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET

app_movies:
    path: /films
    controller: App\Controller\MovieController::index
    methods: GET

app_movies_by_genre:
    path: /films/genre/{genreName}
    controller: App\Controller\MovieController::byGenre
    methods: GET

app_movies_toggle_favorite:
    path: /films/favoris/toggle/{id}
    controller: App\Controller\MovieController::toggleFavorite
    methods: POST

app_movies_toggle_favorite_session:
    path: /films/favoris/session/toggle/{id}
    controller: App\Controller\MovieController::toggleFavoriteSession
    methods: POST

app_test_auth:
    path: /api/test-auth
    controller: App\Controller\MovieController::testAuth
    methods: GET

api_film_favorite:
    path: /api/films/{id}/favorite
    controller: App\Controller\MovieController::apiToggleFavorite
    methods: POST

app_login:
    path: /connexion
    controller: App\Controller\LoginController::login
    methods: [GET, POST]

app_register:
    path: /inscription
    controller: App\Controller\RegistrationController::register
    methods: [GET, POST]

app_logout:
    path: /deconnexion
    controller: App\Controller\LoginController::logout
    methods: GET

admin_films:
    path: /admin/films
    controller: App\Controller\AdminController::index
    methods: GET

admin_film_new:
    path: /admin/films/new
    controller: App\Controller\AdminController::new
    methods: [GET, POST]

admin_film_edit:
    path: /admin/films/{id}/edit
    controller: App\Controller\AdminController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'

admin_film_delete:
    path: /admin/films/{id}/delete
    controller: App\Controller\AdminController::delete
    methods: GET
    requirements:
        id: '\d+'

app_payment:
    path: /paiement
    controller: App\Controller\PaymentController::paiement
    methods: GET

app_payment_validate:
    path: /paiement/valider
    controller: App\Controller\PaymentController::valider
    methods: POST

app_payment_success:
    path: /paiement/succes
    controller: App\Controller\PaymentController::success
    methods: GET

app_cart:
    path: /panier
    controller: App\Controller\CartController::index
    methods: GET

app_cart_add:
    path: /panier/ajouter/{idFilm}
    controller: App\Controller\CartController::add
    methods: GET
    requirements:
        idFilm: '\d+'

app_cart_remove:
    path: /panier/supprimer/{idFilm}
    controller: App\Controller\CartController::remove
    methods: GET
    requirements:
        idFilm: '\d+'

app_cart_clear:
    path: /panier/vider
    controller: App\Controller\CartController::clear
    methods: GET

app_profile:
    path: /profile
    controller: App\Controller\ProfileController::index
    methods: GET

app_favoris:
    path: /profile/favoris
    controller: App\Controller\ProfileController::favoris
    methods: [GET]

app_parametres:
    path: /profile/parametres
    controller: App\Controller\ProfileController::parametres
    methods: [GET]

app_mes_locations:
    path: /profile/locations
    controller: App\Controller\ProfileController::mesLocations
    methods: GET

app_favoris_supprimer:
    path: /profile/favoris/supprimer/{id}
    controller: App\Controller\ProfileController::supprimerFavori
    methods: POST

app_favoris_ajouter:
    path: /profile/favoris/ajouter/{id}
    controller: App\Controller\ProfileController::ajouterFavori
    methods: POST

app_favoris_toggle:
    path: /profile/favoris/toggle/{id}
    controller: App\Controller\ProfileController::toggleFavori
    methods: POST



controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: /