# config/routes/web.yaml
app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: GET

app_movies:
    path: /films
    controller: App\Controller\MovieController::index
    methods: GET

app_profile:
    path: /profile
    controller: App\Controller\ProfileController::index
    methods: [GET]

app_favoris:
    path: /profile/favoris
    controller: App\Controller\ProfileController::favoris
    methods: [GET]

app_parametres:
    path: /profile/parametres
    controller: App\Controller\ProfileController::parametres
    methods: [GET]

app_login:
    path: /connexion
    controller: App\Controller\LoginController::login
    methods: [GET, POST]

app_register:
    path: /inscription
    controller: App\Controller\RegistrationController::register
    methods: [GET, POST]

app_logout:
    path: /deconnexion
    controller: App\Controller\LoginController::logout
    methods: GET

app_add_to_cart:
    path: /api/cart/add
    controller: App\Controller\CartController::add
    methods: [POST]

app_view_cart:
    path: /panier
    controller: App\Controller\CartController::view
    methods: [GET]

admin_films:
    path: /admin/films
    controller: App\Controller\AdminController::index
    methods: GET

admin_film_new:
    path: /admin/films/new
    controller: App\Controller\AdminController::new
    methods: [GET, POST]

admin_film_edit:
    path: /admin/films/{id}/edit
    controller: App\Controller\AdminController::edit
    methods: [GET, POST]
    requirements:
        id: '\d+'

admin_film_delete:
    path: /admin/films/{id}/delete
    controller: App\Controller\AdminController::delete
    methods: GET
    requirements:
        id: '\d+'

# Import automatique des routes des contr√¥leurs avec attributs
controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: /