# config/routes.yaml
controllers:
    resource: ../src/Controller/
    type: attribute
    prefix: /

# Add this to explicitly see if routes are loaded
app_dashboard:
    path: /
    controller: App\Controller\DashboardController::index